# Generated by Django 4.0.1 on 2022-02-23 23:52

from django.db import migrations, models
import main_app.func


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_documenttex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RenameField(
            model_name='documenttex',
            old_name='name',
            new_name='filename',
        ),
        migrations.RemoveField(
            model_name='documenttex',
            name='upload',
        ),
        migrations.AddField(
            model_name='documenttex',
            name='file',
            field=models.FileField(default=0, upload_to=main_app.func.hash_upload),
            preserve_default=False,
        ),
    ]
